# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Anokha CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: git stash
    - run: git pull
    - run: npm ci
    - run: pm2 delete anokha_backend_2024 || true
    - run: touch middleware/RSA/private_key.pem
    - run: touch middleware/RSA/public_key.pem
    - name: Run npm run start
      run: npm run start 
      timeout-minutes: 1
    - run: npm run deploy
